name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "DEV", "square-mages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: |
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Locate and prepare dist folder
        run: |
          # Find the actual output directory
          if [ -d "dist/xoo-creator/browser" ]; then
            DIST_DIR="dist/xoo-creator/browser"
          elif [ -d "dist/xoo-creator" ]; then
            DIST_DIR="dist/xoo-creator"
          else
            echo "Could not find dist directory"
            find dist -type d -name "*" || true
            exit 1
          fi
          echo "Using dist directory: $DIST_DIR"
          
          # Add SPA fallback
          cp "$DIST_DIR/index.html" "$DIST_DIR/404.html"
          
          # Disable Jekyll processing
          touch "$DIST_DIR/.nojekyll"
          
          echo "DIST_DIR=$DIST_DIR" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DIST_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
