name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "DEV", "square-mages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: |
          npm run build -- --base-href "./"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Locate dist folder
        id: dist
        shell: bash
        run: |
          set -e
          FIRST_INDEX=$(find dist -type f -name index.html | head -n 1)
          if [ -z "$FIRST_INDEX" ]; then
            echo "No index.html found under dist" >&2
            exit 1
          fi
          DIST_DIR=$(dirname "$FIRST_INDEX")
          echo "DIST_DIR=$DIST_DIR" >> $GITHUB_OUTPUT
          echo "Using DIST_DIR=$DIST_DIR"

      - name: Add SPA fallback (404.html)
        run: |
          cp "${{ steps.dist.outputs.DIST_DIR }}"/index.html "${{ steps.dist.outputs.DIST_DIR }}"/404.html

      - name: Disable Jekyll processing
        run: |
          touch "${{ steps.dist.outputs.DIST_DIR }}"/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.dist.outputs.DIST_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
